kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Chart.Name }}-{{ .Values.frontend.name }}-service
  labels:
    {{- include "springboot-angular-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "springboot-angular-app.labels" . | nindent 4 }}
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: port-http-frontend
      protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: http-frontend
