FROM node:18-alpine

MAINTAINER cismael

# label to link the generated package from this Dockerfile to the github repository that containt the source code
LABEL org.opencontainers.image.source https://github.com/cismael/springboot-angular-app

WORKDIR /app

COPY . /app/

RUN npm install -g @angular/cli

USER 1000

ENTRYPOINT npm run start
