### STAGE 1: Build ###
FROM node:21-alpine

MAINTAINER cismael

# label to link the generated package from this Dockerfile to the github repository that containt the source code
LABEL org.opencontainers.image.source https://github.com/cismael/springboot-angular-app

WORKDIR /app

COPY src/ /app/src/
COPY package*.json  /app/
COPY tsconfig*.json  /app/

RUN npm install -g @angular/cli && \
    npm ci --only=production

USER 1000

ENTRYPOINT npm run start
