version: "3.9"

services:

  # The backend app
  backend-users-api:
    build:
      context: ./back-end
      dockerfile: Dockerfile-build
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 350M
    restart: always

  # The frontend app
  frontend:
    build:
      context: ./front-end
      dockerfile: front-end/Dockerfile-build-v1
    ports:
      - "4200:80"
    deploy:
      resources:
        limits:
          memory: 350M
    restart: always
    depends_on:
      - "backend-users-api"
