kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Chart.Name }}-{{ .Values.backend.name }}-deployment
  labels:
    app: {{ .Chart.Name }}-{{ .Values.backend.name }}
    {{- include "springboot-angular-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Values.backend.name }}
      {{- include "springboot-angular-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Values.backend.name }}
        {{- include "springboot-angular-app.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.backend.name }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: {{ .Values.backend.service.targetPort }}
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.image.resources | nindent 12 }}
