### STAGE 1: Build ###
FROM maven:3.9-amazoncorretto-21 AS builder

WORKDIR /app

COPY . /app/

RUN mvn clean install

### STAGE 2: Run ###
FROM amazoncorretto:21.0.1-alpine

MAINTAINER cismael

# label to link the generated package from this Dockerfile to the github repository that containt the source code
LABEL org.opencontainers.image.source https://github.com/cismael/springboot-angular-app

COPY --from=builder /app/users/users-api/target/users-api-*.jar /app/users-api.jar

EXPOSE 8081

USER 1000

CMD java -jar /app/users-api.jar
