### STAGE 1: Build ###
FROM node:18-alpine AS builder

WORKDIR /app

COPY . /app/

RUN npm run build:prod

### STAGE 2: Run ###
FROM nginx:1.23-alpine

MAINTAINER cismael

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/springboot-angular-app-frontend /usr/share/nginx/html
