### STAGE 1: Build ###
FROM node:18-alpine AS build

WORKDIR /app

COPY . /app/

RUN npm run build:prod

### STAGE 2: Run ###
FROM nginx:1.23-alpine

COPY --from=build /app/dist/springboot-angular-app-frontend /usr/share/nginx/html
