### STAGE 1: Build ###
FROM node:18-alpine

MAINTAINER cismael

WORKDIR /app

COPY src/ /app/src/
COPY package*.json  /app/
COPY tsconfig*.json  /app/

RUN npm install -g @angular/cli && \
    npm ci

USER 1000

ENTRYPOINT npm run start
