### STAGE 1: Build ###
FROM maven:3.8-amazoncorretto-17 AS builder

WORKDIR /app

COPY . /app/

RUN mvn clean install

### STAGE 2: Run ###
FROM amazoncorretto:19-alpine

MAINTAINER cismael

COPY --from=builder /app/users/users-api/target/users-api-*.jar /app/users-api.jar

EXPOSE 8081

USER 1000

CMD java -jar /app/users-api.jar
