kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Chart.Name }}-{{ .Values.backend.name }}-ingress
  labels:
    {{- include "springboot-angular-app.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Chart.Name }}.{{ .Values.ingress.domainName }}
    {{ if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{ end }}
spec:
  rules:
    - host: {{ .Chart.Name }}.{{ .Values.ingress.domainName }}
      http:
        paths:
          # frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-{{ .Values.frontend.name }}-service
                port:
                  number: {{ .Values.frontend.service.port }}
          # backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-{{ .Values.backend.name }}-service
                port:
                  number: {{ .Values.backend.service.port }}
