version: "3.9"

services:

  # The backend app
  backend-users-api:
    container_name: backend-users-api-build-v1
    build:
      context: ../backend/users/users-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 128M
        limits:
          cpus: "0.1"
          memory: 512M
    restart: always

  # The frontend app
  frontend:
    container_name: frontend-build-v1
    build:
      context: ../frontend
      dockerfile: Dockerfile-build-v1
    ports:
      - "4200:80"
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 128M
        limits:
          cpus: "0.1"
          memory: 512M
    restart: always
    depends_on:
      - "backend-users-api"
