#!/bin/bash

################################################################################## Source needed variables and functions
source variables
source secrets
source functions_backend
source functions_docker
source functions_frontend
source functions_helm
source functions_kubernetes
source functions_utilities
