#!/bin/bash

##################################################################################################### App name variables
# Backend varible(s)
BACKEND_FOLDER_NAME="backend"
BACKEND_DOCKER_IMAGE_NAME="springboot-angular-app-backend"

# Frontend varible(s)
FRONTEND_DOCKER_IMAGE_NAME="springboot-angular-app-frontend"
FRONTEND_FOLDER_NAME="frontend"

############################################################################################### Declare needed variables
# Container registry owner username
CONTAINER_REGISTRY_OWNER_USERNAME="cismael"

#################################################################################################### DockerHub variables
# DockerHub container registry URL
#DOCKERHUB_CONTAINER_REGISTRY_URL="registry-1.docker.io"
DOCKERHUB_CONTAINER_REGISTRY_URL="docker.io"

####################################################################################################### GitHub variables
# Github container registry URL
GITHUB_CONTAINER_REGISTRY_URL="ghcr.io"

######################################################################################################### Helm variables
# Possible environment values
ENVIRONMENTS="dev staging prod"

# Helm chart directory path
HELM_CHART_DIR=".k8s/helm-chart"
